language: python
dist: bionic
python:
    - "3.6"
    - "3.7"
    - "3.8"
before_install:
    - pip install -U pip setuptools
    - pip install -U tox tox-travis
install:
    - pip install -r test-requirements.pip
script:
    - tox
after_success:
  # Report coverage results to coveralls.io
  - pip install coveralls
  - coveralls
matrix:
  fast_finish: true
  include:
  - python: 3.8
    env: TOXENV=flake8
